/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ImageIcon;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.OverlayLayout;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;


/**
 *
 * @author Willian
 */
public class JPanelPrincipal extends javax.swing.JFrame {

	TelConf telaConf = new TelConf();
	// Cor quando o mouse entrar no JButton
	int ec = 103, ec1 = 103, ec2 = 103;
	// Cor quando o mouse sair do JButton
	int sc = 51, sc1 = 51, sc2 = 51;
	// NÃºmero do JButton clicado
	private int num = 2;

	private final String img = "/com/images/images_1.png";

	// ####################################################################################################################
	//
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton JButtonAddUsuarios;
	private JButton JButtonVeiculos;
	private JButton JButtonClientes;
	private JButton JButtonConfiguracao;
	private JButton JButtonFaturamento;
	private JButton JButtonHome;
	private JButton JButtonMenuBar;
	private JButton JButtonOS;
	private JButton JButtonOrcamento;
	private JButton jButton10;
	private JButton jButton11;
	private JLabel JLabelFundoJPanelHome;
	private JLabel JLabelIconeUsuario;
	private JLabel JLabelNomeUsuario;
	private JPanel JPanelCenter;
	private JPanel JPanelNorth;
	private JPanel JPanelHome;
	private JPanel JPanelWestMenuLateral;
	private JPanel JPanelJButtonConfiguracao;
	private JPanel JPanelButtons;
	private JPanel JPanelHomeInicial;
	private JPanel JPanelWest;
	private javax.swing.JScrollPane JScrollWest;

	// End of variables declaration//GEN-END:variables
	/**
	 * Creates new form TelaPrincipal
	 */
	public JPanelPrincipal() {
		initComponents(); // inicializa os componentes da JFrame.
		// Metodo para configurar preferencias de componentes de JFrame.
		this.inicializeAplication();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	/**
	 * 
	 */
	/**
	 * 
	 */
	private void initComponents() {
		// ##Parte West do JPanelPrincipal##
		this.getJButtonHome();
		this.getJButtonOS();
		this.getJButtonOrcamento();
		this.getJButtonVeiculos();
		this.getJButtonClientes();
		this.getJButtonFaturamento();
		this.getJButtonAddUsuarios();
		this.getJButtonConfiguracao();
		this.getJPanelJButtonConfiguracao();		
		this.getJPanelButtons();
		
		this.getJScrollWest();
		this.getJScrollWestAddComponentes();
		
		this.getJPanelButtons();
		this.getJPanelButtonConfiguracaoAddComponentes();
		
		this.getJLabelIconeUsuario();
		this.getJLabelNomeUsuario();
		
		this.getJPanelWest();
		this.getJPanelWestAddComponentes();
		
		this.getJPanelWestMenuLateral();
		this.getJPanelWestMenuLateralAddComponentes();
		
		// ##Parte North do JPanelPrincipal##
		this.getJButtonMenuBar();
		this.getJPanelNorth();
		this.getJPanelNorthtAddComponentes();
		
		// ##Parte Center do JPanelPrincipal##
		this.getJLabelFundoJPanelHome();
		this.getJPanelHome();
		this.getJPanelHomeInicialAddComponentes();
		this.getJPanelCenter();
		this.getJPanelCenterAddComponentes();

	}
	

	private void inicializeAplication() {
		telaConf.fullScree(this);
	}

	private void open(JPanel panel, int wdt_close, int wdt_open, int hgt) {
		panel.setSize(wdt_close, hgt);
		Thread thread;
		thread = new Thread() {

			@Override
			public void run() {
				try {
					for (int i = wdt_close; i <= wdt_open; i++) {
						Thread.sleep(1);
						panel.setSize(i, hgt);
					}
				} catch (Exception e) {
					JOptionPane.showMessageDialog(null, e);
				}
			}
		};
		thread.start();
	}

	private void close(JPanel panel, int wdt_close, int wdt_open, int hgt) {
		panel.setSize(wdt_open, hgt);
		Thread thread;
		thread = new Thread() {

			@Override
			public void run() {
				try {
					for (int i = wdt_open; i >= wdt_close; i--) {
						Thread.sleep(1);
						panel.setSize(i, hgt);
					}
				} catch (Exception e) {
					JOptionPane.showMessageDialog(null, e);
				}
			}
		};
		thread.start();

	}


	private void btnClick(int num) {
		this.num = num;
		if (num != 1)
			this.setColor(51, 51, 51);
		int c = 103;
		int c1 = 103;
		int c2 = 103;
		switch (num) {
		case 1:
			this.JButtonMenuBar.setBackground(new Color(109, 65, 0));
			break;
		case 2:
			this.JButtonHome.setBackground(new Color(c, c1, c2));
			break;
		case 3:
			this.JButtonOS.setBackground(new Color(c, c1, c2));
			break;
		case 4:
			this.JButtonOrcamento.setBackground(new Color(c, c1, c2));
			break;
		case 5:
			this.JButtonVeiculos.setBackground(new Color(c, c1, c2));
			break;
		case 6:
			this.JButtonClientes.setBackground(new Color(c, c1, c2));
			break;
		case 7:
			this.JButtonAddUsuarios.setBackground(new Color(c, c1, c2));
			break;
		case 8:
			this.JButtonFaturamento.setBackground(new Color(c, c1, c2));
			break;

		case 9:
			this.JButtonConfiguracao.setBackground(new Color(c, c1, c2));
			break;
		}
	}

	private void setColor(int c, int c1, int c2) {
		this.JButtonHome.setBackground(new Color(c, c1, c2));
		this.JButtonOS.setBackground(new Color(c, c1, c2));
		this.JButtonOrcamento.setBackground(new Color(c, c1, c2));
		this.JButtonVeiculos.setBackground(new Color(c, c1, c2));
		this.JButtonClientes.setBackground(new Color(c, c1, c2));
		this.JButtonAddUsuarios.setBackground(new Color(c, c1, c2));
		this.JButtonFaturamento.setBackground(new Color(c, c1, c2));
		this.JButtonConfiguracao.setBackground(new Color(c, c1, c2));
	}

	private void mouseExited(JButton btn, int numEx) {
		System.out.format("mouseExited: num = %s, numEx = %s", (int) num, (int) numEx);
		if (num != numEx) {
			btn.setBackground(new Color(sc, sc1, sc2));
		}
	}
	
	
	
	public JPanelPrincipal getJPanelPrincipal() {
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		setBackground(new Color(255, 255, 255));
		setFocusCycleRoot(false);
		setFocusable(false);
		setFocusableWindowState(false);
		setLocationByPlatform(true);
		setPreferredSize(new Dimension(800,600));
		setSize(new Dimension(1225, 937));
		return this;
	}

	
	public JLabel getJLabelIconeUsuario() {
		if(JLabelIconeUsuario == null){
			JLabelIconeUsuario = new JLabel();
			JLabelIconeUsuario.setHorizontalAlignment(SwingConstants.CENTER);
			JLabelIconeUsuario.setIcon(new ImageIcon(getClass().getResource("/com/icons/user_100.png")));
		}
		return JLabelIconeUsuario;
	}
	

	public JLabel getJLabelNomeUsuario() {
		if(JLabelNomeUsuario == null){
			JLabelNomeUsuario = new JLabel();
			JLabelNomeUsuario.setFont(new Font("Arial", 1, 24));
			JLabelNomeUsuario.setForeground(new Color(255, 255, 255));
			JLabelNomeUsuario.setHorizontalAlignment(SwingConstants.CENTER);
			JLabelNomeUsuario.setText("Usuário");
			JLabelNomeUsuario.setHorizontalTextPosition(SwingConstants.CENTER);

		}
		return JLabelNomeUsuario;
	}
	

	public JButton getJButtonMenuBar() {
		if (JButtonMenuBar == null) {
			JButtonMenuBar = new JButton();
			JButtonMenuBar.setBackground(new Color(219, 131, 0));
			JButtonMenuBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/menu_64.png"))); // NOI18N
			JButtonMenuBar.setBorder(null);
			JButtonMenuBar.setBorderPainted(false);
			JButtonMenuBar.setContentAreaFilled(false);
			JButtonMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonMenuBar.setDisabledIcon(null);
			JButtonMenuBar.setDisabledSelectedIcon(null);
			JButtonMenuBar.setOpaque(true);
			
		}
		return JButtonMenuBar;
	}

	
	public JButton getJButtonHome() {
		if (JButtonHome == null) {
			JButtonHome = new JButton();
			JButtonHome.setBackground(new Color(103, 103, 103));
			JButtonHome.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			JButtonHome.setForeground(new Color(204, 204, 204));
			JButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/home_48.png"))); // NOI18N
			JButtonHome.setText(" Iniciar");
			JButtonHome.setBorder(null);
			JButtonHome.setBorderPainted(false);
			JButtonHome.setContentAreaFilled(false);
			JButtonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonHome.setHideActionText(true);
			JButtonHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			JButtonHome.setOpaque(true);
		}
		return JButtonHome;
	}
		
	
	public JButton getJButtonOS() {
		if (JButtonOS == null) {
			JButtonOS = new JButton();
			JButtonOS.setBackground(new Color(51, 51, 51));
			JButtonOS.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			JButtonOS.setForeground(new Color(204, 204, 204));
			JButtonOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/OS_48.png"))); // NOI18N
			JButtonOS.setText(" O.S");
			JButtonOS.setBorder(null);
			JButtonOS.setBorderPainted(false);
			JButtonOS.setContentAreaFilled(false);
			JButtonOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonOS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			JButtonOS.setOpaque(true);
		}
		return JButtonOS;
	}
	
	
	public JButton getJButtonOrcamento() {
		if (JButtonOrcamento == null) {
			JButtonOrcamento = new JButton();
			JButtonOrcamento.setBackground(new Color(51, 51, 51));
			JButtonOrcamento.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			JButtonOrcamento.setForeground(new Color(204, 204, 204));
			JButtonOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/orca_car_48.png"))); // NOI18N
			JButtonOrcamento.setText(" OrÃ§amento");
			JButtonOrcamento.setBorder(null);
			JButtonOrcamento.setBorderPainted(false);
			JButtonOrcamento.setContentAreaFilled(false);
			JButtonOrcamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonOrcamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			JButtonOrcamento.setOpaque(true);
		}
		return JButtonOrcamento;
	}
	
	
	public JButton getJButtonVeiculos() {
		if (JButtonVeiculos == null) {
			JButtonVeiculos = new JButton();
			JButtonVeiculos.setBackground(new Color(51, 51, 51));
			JButtonVeiculos.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			JButtonVeiculos.setForeground(new Color(204, 204, 204));
			JButtonVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/car_48_1.png"))); // NOI18N
			JButtonVeiculos.setText(" Ve\u00EDculos");
			JButtonVeiculos.setBorder(null);
			JButtonVeiculos.setBorderPainted(false);
			JButtonVeiculos.setContentAreaFilled(false);
			JButtonVeiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonVeiculos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		}
		return JButtonVeiculos;
	}
	

	public JButton getJButtonClientes() {
		if (JButtonClientes == null) {
			JButtonClientes = new JButton();
			JButtonClientes.setBackground(new Color(51, 51, 51));
			JButtonClientes.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			JButtonClientes.setForeground(new Color(204, 204, 204));
			JButtonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/users_48.png"))); // NOI18N
			JButtonClientes.setText(" Clientes");
			JButtonClientes.setBorder(null);
			JButtonClientes.setBorderPainted(false);
			JButtonClientes.setContentAreaFilled(false);
			JButtonClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			JButtonClientes.setOpaque(true);
		}
		return JButtonClientes;
	}

	
	public JButton getJButtonFaturamento() {
		if (JButtonFaturamento == null) {
			JButtonFaturamento = new JButton();
			JButtonFaturamento.setBackground(new Color(51, 51, 51));
			JButtonFaturamento.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); 
			JButtonFaturamento.setForeground(new Color(204, 204, 204));
			JButtonFaturamento.setIcon(new ImageIcon(getClass().getResource("/com/icons/estimate-48.png"))); 
			JButtonFaturamento.setText(" Faturamento");
			JButtonFaturamento.setBorder(null);
			JButtonFaturamento.setBorderPainted(false);
			JButtonFaturamento.setContentAreaFilled(false);
			JButtonFaturamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonFaturamento.setHorizontalAlignment(SwingConstants.LEFT);
			JButtonFaturamento.setOpaque(true);
			
		}
		return JButtonFaturamento;
	}

	
	public JButton getJButtonAddUsuarios() {
		if (JButtonAddUsuarios == null) {
			JButtonAddUsuarios = new JButton();
			JButtonAddUsuarios.setBackground(new Color(51, 51, 51));
			JButtonAddUsuarios.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			JButtonAddUsuarios.setForeground(new Color(204, 204, 204));
			JButtonAddUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/use_conf_48.png"))); // NOI18N
			JButtonAddUsuarios.setText(" UsuÃ¡rio");
			JButtonAddUsuarios.setBorder(null);
			JButtonAddUsuarios.setBorderPainted(false);
			JButtonAddUsuarios.setContentAreaFilled(false);
			JButtonAddUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonAddUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			JButtonAddUsuarios.setOpaque(true);
			
		}
		return JButtonAddUsuarios;
	}
	
			
	public JButton getJButtonConfiguracao() {
		if (JButtonConfiguracao == null) {
			JButtonConfiguracao = new JButton();
			JButtonConfiguracao.setBackground(new Color(51, 51, 51));
			JButtonConfiguracao.setFont(new Font("Trebuchet MS", 1, 18));
			JButtonConfiguracao.setForeground(new Color(204, 204, 204));
			JButtonConfiguracao.setIcon(new ImageIcon(getClass().getResource("/com/icons/conf_48.png")));
			JButtonConfiguracao.setText(" Configurações");
			JButtonConfiguracao.setBorder(null);
			JButtonConfiguracao.setBorderPainted(false);
			JButtonConfiguracao.setContentAreaFilled(false);
			JButtonConfiguracao.setCursor(new Cursor(Cursor.HAND_CURSOR));
			JButtonConfiguracao.setHorizontalAlignment(SwingConstants.LEFT);
			JButtonConfiguracao.setOpaque(true);
			
		}
		return JButtonConfiguracao;
	}

	
	public JButton getjButton10() {
		if (jButton10 == null) {
			jButton10 = new JButton();
			jButton10.setBackground(new Color(204, 204, 204));
			jButton10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			jButton10.setText(" Cliente");
			jButton10.setBorder(null);
			jButton10.setBorderPainted(false);
			jButton10.setContentAreaFilled(false);
			jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			jButton10.setOpaque(true);
		}
		return jButton10;
	}


	public JButton getjButton11() {
		if (jButton11 == null) {
			jButton11 = new JButton();
			jButton11.setBackground(new Color(204, 204, 204));
			jButton11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			jButton11.setText(" Cliente");
			jButton11.setBorder(null);
			jButton11.setBorderPainted(false);
			jButton11.setContentAreaFilled(false);
			jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			jButton11.setOpaque(true);
		}
		return jButton11;
	}

	
	public JPanel getJPanelWestMenuLateral() {
		if(JPanelWestMenuLateral == null){
			JPanelWestMenuLateral = new JPanel();
			JPanelWestMenuLateral.setBackground(new Color(51, 51, 51));
			JPanelWestMenuLateral.setPreferredSize(new Dimension(265, 800));

		}
		return JPanelWestMenuLateral;
	}

	
	public JPanel getJPanelWest() { //JPanelWest contém os dados do usuários de login
		if(JPanelWest == null){
			JPanelWest = new JPanel();
			JPanelWest.setBackground(new Color(0, 51, 51));
			JPanelWest.setBorder(null);
			JPanelWest.setOpaque(false);
			JPanelWest.setPreferredSize(new Dimension(265, 200));
		}
		return JPanelWest;
	}

	
	public JScrollPane getJScrollWest() {
		if(JScrollWest == null){
			JScrollWest = new JScrollPane();
			JScrollWest.setBackground(new Color(51, 51, 51));
			JScrollWest.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
			JScrollWest.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
			JScrollWest.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
			JScrollWest.setViewportBorder(null);
			JScrollWest.setAutoscrolls(true);
			JScrollWest.setCursor(new Cursor(Cursor.HAND_CURSOR));
			JScrollWest.setFocusCycleRoot(true);
			JScrollWest.setOpaque(true);
			JScrollWest.setPreferredSize(new Dimension(265, 1100));

		}
		return JScrollWest;
	}
	

	public JPanel getJPanelButtons() {
		if(JPanelButtons == null){
			JPanelButtons = new JPanel();
			JPanelButtons.setBackground(new Color(51, 51, 51));
			JPanelButtons.setBorder(null);
			JPanelButtons.setPreferredSize(new Dimension(265, 825));

		}
		return JPanelButtons;
	}
	
	
	public void getJPanelPrincipalAddComponentes() {
		getContentPane().add(JPanelWestMenuLateral, BorderLayout.WEST);
		getContentPane().add(JPanelNorth, BorderLayout.NORTH);
		getContentPane().add(JPanelCenter, BorderLayout.CENTER);
	}
	
	
	public void getJPanelHomeInicialAddComponentes() {
		JPanelHomeInicial.add(JLabelFundoJPanelHome, BorderLayout.CENTER);
	}
	
	
	public void getJPanelCenterAddComponentes() {
		JPanelCenter.add(JPanelHomeInicial);
	}
	
	
	public void getJPanelWestMenuLateralAddComponentes() {
		GroupLayout JPanelWestMenuLateral_Layout = new GroupLayout(JPanelWestMenuLateral);
		JPanelWestMenuLateral.setLayout(JPanelWestMenuLateral_Layout);
		JPanelWestMenuLateral_Layout.setHorizontalGroup(
				JPanelWestMenuLateral_Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addComponent(JPanelWest, GroupLayout.PREFERRED_SIZE,
								GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(JScrollWest, GroupLayout.PREFERRED_SIZE,
								GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE));
		JPanelWestMenuLateral_Layout.setVerticalGroup(
				JPanelWestMenuLateral_Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(JPanelWestMenuLateral_Layout.createSequentialGroup()
								.addComponent(JPanelWest, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(JScrollWest, GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)));
	}
		
	
	public void getJPanelWestAddComponentes() {
		GroupLayout JPanelWest_Layout = new GroupLayout(JPanelWest);
		JPanelWest.setLayout(JPanelWest_Layout);
		JPanelWest_Layout.setHorizontalGroup(JPanelWest_Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addComponent(JLabelNomeUsuario, GroupLayout.DEFAULT_SIZE,
						GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(JPanelWest_Layout
						.createSequentialGroup().addContainerGap(82, Short.MAX_VALUE).addComponent(JLabelIconeUsuario,
								GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(83, Short.MAX_VALUE)));
		JPanelWest_Layout.setVerticalGroup(JPanelWest_Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(JPanelWest_Layout.createSequentialGroup().addContainerGap(31, Short.MAX_VALUE)
						.addComponent(JLabelIconeUsuario, GroupLayout.PREFERRED_SIZE, 96,
								GroupLayout.PREFERRED_SIZE)
						.addGap(5, 5, 5)
						.addComponent(JLabelNomeUsuario, GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
						.addGap(12, 12, 12)));
	}
	
	
	public void getJScrollWestAddComponentes() {
		JScrollWest.setViewportView(JPanelButtons);
	}
	
	
	public void JPanelButtonsAddComponentes() {
		GroupLayout JPanelButtons_Layout = new GroupLayout(JPanelButtons);
		JPanelButtons_Layout.setHorizontalGroup(JPanelButtons_Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(JPanelButtons_Layout.createSequentialGroup().addContainerGap()
						.addGroup(JPanelButtons_Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(JPanelButtons_Layout.createParallelGroup(Alignment.TRAILING)
										.addComponent(JButtonOS, GroupLayout.PREFERRED_SIZE, 219,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(JButtonHome, GroupLayout.PREFERRED_SIZE, 219,
												GroupLayout.PREFERRED_SIZE))
								.addComponent(JButtonFaturamento, GroupLayout.PREFERRED_SIZE, 219,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(JButtonOrcamento, GroupLayout.PREFERRED_SIZE, 219,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(JButtonVeiculos, GroupLayout.PREFERRED_SIZE, 219,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(JButtonClientes, GroupLayout.PREFERRED_SIZE, 219,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(JButtonAddUsuarios, GroupLayout.PREFERRED_SIZE, 219,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(JButtonConfiguracao, GroupLayout.PREFERRED_SIZE, 219,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(JPanelJButtonConfiguracao, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addContainerGap(32, Short.MAX_VALUE)));
		JPanelButtons_Layout.setVerticalGroup(JPanelButtons_Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(JPanelButtons_Layout.createSequentialGroup().addGap(6)
						.addComponent(JButtonHome, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(JButtonOS, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(JButtonOrcamento, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(JButtonVeiculos, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(JButtonClientes, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
						.addGap(7)
						.addComponent(JButtonAddUsuarios, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
						.addGap(13)
						.addComponent(JButtonFaturamento, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(JButtonConfiguracao, GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE).addGap(168)
						.addComponent(JPanelJButtonConfiguracao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		JPanelButtons.setLayout(JPanelButtons_Layout);

	}

	
				
	public void getJPanelNorthtAddComponentes() {
		GroupLayout JPanelNorth_Layout = new GroupLayout(JPanelNorth);
		JPanelNorth.setLayout(JPanelNorth_Layout);
		JPanelNorth_Layout
				.setHorizontalGroup(JPanelNorth_Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(JPanelNorth_Layout.createSequentialGroup()
								.addComponent(JButtonMenuBar, GroupLayout.PREFERRED_SIZE, 65,
										GroupLayout.PREFERRED_SIZE)
								.addContainerGap(1142, Short.MAX_VALUE)));
		JPanelNorth_Layout.setVerticalGroup(JPanelNorth_Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(JPanelNorth_Layout.createSequentialGroup().addComponent(JButtonMenuBar,
						GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

	}
	
	
	public void getJPanelButtonConfiguracaoAddComponentes() {
		GroupLayout JPanelButtonConfiguracao_Layout = new GroupLayout(JPanelJButtonConfiguracao);
		JPanelJButtonConfiguracao.setLayout(JPanelButtonConfiguracao_Layout);
		JPanelButtonConfiguracao_Layout.setHorizontalGroup(
				JPanelButtonConfiguracao_Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(JPanelButtonConfiguracao_Layout.createSequentialGroup().addGap(1, 1, 1)
								.addGroup(JPanelButtonConfiguracao_Layout
										.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(jButton10, GroupLayout.PREFERRED_SIZE, 219,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jButton11, GroupLayout.PREFERRED_SIZE, 219,
												GroupLayout.PREFERRED_SIZE))
								.addGap(1, 1, 1)));
		
		
		JPanelButtonConfiguracao_Layout.setVerticalGroup(
				JPanelButtonConfiguracao_Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(JPanelButtonConfiguracao_Layout.createSequentialGroup().addGap(1, 1, 1)
								.addComponent(jButton10, GroupLayout.PREFERRED_SIZE, 42,
										GroupLayout.PREFERRED_SIZE)
								.addGap(1, 1, 1).addComponent(jButton11, GroupLayout.PREFERRED_SIZE, 42,
										GroupLayout.PREFERRED_SIZE)
								.addGap(1, 1, 1)));
	}
	
	
	public JLabel getJLabelFundoJPanelHome() {
		if(JLabelFundoJPanelHome == null){
			JLabelFundoJPanelHome = new JLabel();
			JLabelFundoJPanelHome.setBackground(new Color(255, 255, 255));
			JLabelFundoJPanelHome.setForeground(new Color(102, 102, 102));
			JLabelFundoJPanelHome.setHorizontalAlignment(SwingConstants.CENTER);
			JLabelFundoJPanelHome.setIcon(new ImageIcon(getClass().getResource("/com/images/images_1.png")));
			JLabelFundoJPanelHome.setHorizontalTextPosition(SwingConstants.CENTER);
			JLabelFundoJPanelHome.setOpaque(true);
		}
		return JLabelFundoJPanelHome;
	}
	
	

	public JPanel getJPanelCenter() {
		if(JPanelCenter == null){
			JPanelCenter = new JPanel();
			JPanelCenter.setBackground(new Color(255, 255, 255));
			JPanelCenter.setLayout(new OverlayLayout(JPanelCenter));
		}
		return JPanelCenter;
	}
	
	

	public JPanel getJPanelNorth() {
		if(JPanelNorth == null){
			JPanelNorth = new JPanel();
			JPanelNorth.setBackground(new Color(219, 131, 0));
			JPanelNorth.setPreferredSize(new Dimension(1027, 60));
		}
		return JPanelNorth;
	}
	
	

	public JPanel getJPanelHome() {
		if(JPanelHome == null){
			JPanelHome = new JPanel();
			JPanelHome.setLayout(new BorderLayout());
			
		}
		return JPanelHome;
	}
	
	

	public JPanel getJPanelJButtonConfiguracao() {
		if(JPanelJButtonConfiguracao == null){
			JPanelJButtonConfiguracao = new JPanel();
			JPanelJButtonConfiguracao.setBackground(new Color(0, 0, 0));
			JPanelJButtonConfiguracao.setRequestFocusEnabled(false);
			JPanelJButtonConfiguracao.setVisible(false);
		}
		return JPanelJButtonConfiguracao;
	}
	
	

	public JPanel getPnl_iniciar() {
		if(JPanelHomeInicial == null){
			JPanelHomeInicial = new JPanel();
			JPanelHomeInicial.setLayout(new BorderLayout());		
			
		}
		return JPanelHomeInicial;
	}
	
		
	
}


