



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.KeyEvent;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author willi
 */
public class JPanelLogin extends JFrame {

	
    // declaracao de variaveis inicio
    JButton btnEntrar;
    JButton jButton1;
    JLabel jLabel2;
    JPanel jPanel1;
    JPanel jPanel2;
    JPanel jPanel3;
    JPanel jPanel4;
    JLabel lblIcon;
    JLabel lblImageFrame;
    JLabel lblImagemPnl;
    JLabel jLabelSenha;
    JLabel lblSenhaErro;
    JLabel lblUsuario;
    JPanel pnlLogin;
    JPanel pnlPrincipalFrame;
    JTextField txfUsuario;
    JPasswordField txfsenha;
    // declaracao de variaveis final
	
   
    /** Creates new form TelaLogin */
    // Inicializando atributos com os caminhos das imagens na pasta.
    final String img = "/com/images/funTel1.jpg";
    private final String img1 = "/com/images/funLogin.png";
    private final String img2 = "/com/images/iconPrj.png";
    
    // Cria objeto da classe TelConf.
    TelConf telaConf = new TelConf();    
    
    public JPanelLogin() { // Método construtor.
        initComponents(); // inicializa os componentes da JFrame.
        // Chama o metodo a baixo para renderização da imagem de fundo da tela
        // login.
        this.imgJFrameLogin(true);
        // Metodo para configurar preferencias de componentes de JFrame.
        this.inicializeAplication();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new JButton();
        jLabel2 = new JLabel();
        pnlPrincipalFrame = new JPanel();
        jPanel4 = new JPanel();
        pnlLogin = new JPanel();
        jPanel1 = new JPanel();
        lblIcon = new JLabel();
        jPanel2 = new JPanel();
        lblUsuario = new JLabel();
        txfUsuario = new JTextField();
        jLabelSenha = new JLabel();
        txfsenha = new JPasswordField();
        jPanel3 = new JPanel();
        lblSenhaErro = new JLabel();
        btnEntrar = new JButton();
        lblImagemPnl = new JLabel();
        lblImageFrame = new JLabel();

        jButton1.setText("jButton1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setType(java.awt.Window.Type.POPUP);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        pnlPrincipalFrame.setOpaque(false);
        pnlPrincipalFrame.setLayout(new java.awt.GridBagLayout());

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(390, 500));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setLayout(null);

        pnlLogin.setBackground(new java.awt.Color(28, 178, 188));
        pnlLogin.setForeground(new java.awt.Color(168, 168, 168));
        pnlLogin.setAutoscrolls(true);
        pnlLogin.setOpaque(false);
        pnlLogin.setPreferredSize(new java.awt.Dimension(390, 440));
        pnlLogin.setLayout(new java.awt.BorderLayout());

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setOpaque(false);

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/iconPrj.png"))); // NOI18N
        lblIcon.setToolTipText("");
        lblIcon.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblIcon.setInheritsPopupMenu(false);
        lblIcon.setMinimumSize(new java.awt.Dimension(110, 110));
        lblIcon.setPreferredSize(new java.awt.Dimension(380, 110));
        lblIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lblIcon);

        pnlLogin.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(380, 220));
        jPanel2.setRequestFocusEnabled(false);

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("Usuário:");

        txfUsuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txfUsuario.setPreferredSize(new java.awt.Dimension(205, 55));

        jLabelSenha.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(204, 204, 204));
        jLabelSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSenha.setText("Senha:");

        txfsenha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txfsenha.setPreferredSize(new java.awt.Dimension(205, 55));
        txfsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER){
                    if(txfsenha.getText().equals("654987")){
                        btnEntrar.doClick();
                    }else{
                        lblSenhaErro.setVisible(true);
                    }
                }
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsuario)
                    .addComponent(jLabelSenha))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfsenha, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSenha))
                .addGap(32, 32, 32))
        );

        pnlLogin.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(380, 105));

        lblSenhaErro.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblSenhaErro.setForeground(new java.awt.Color(255, 0, 0));
        lblSenhaErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSenhaErro.setText("Usuário e/ou senha iconrretos");
        lblSenhaErro.setToolTipText("");
        lblSenhaErro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSenhaErro.setPreferredSize(new java.awt.Dimension(380, 35));
        lblSenhaErro.setVisible(false);

        btnEntrar.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(null);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblSenhaErro, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblSenhaErro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlLogin.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel4.add(pnlLogin);
        pnlLogin.setBounds(0, 0, 390, 430);
        pnlLogin.getAccessibleContext().setAccessibleName("");

        lblImagemPnl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/funLogin.png"))); // NOI18N
        jPanel4.add(lblImagemPnl);
        lblImagemPnl.setBounds(0, 0, 130, 120);

        pnlPrincipalFrame.add(jPanel4, new java.awt.GridBagConstraints());

        getContentPane().add(pnlPrincipalFrame);
        pnlPrincipalFrame.getAccessibleContext().setAccessibleDescription("");

        lblImageFrame.setRequestFocusEnabled(false);
        getContentPane().add(lblImageFrame);

        getAccessibleContext().setAccessibleParent(pnlPrincipalFrame);

        setSize(new java.awt.Dimension(1260, 801));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // Quando o btnEntrar for Clicado.
        this.dispose();
        new JPanelPrincipal().setVisible(true);
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // Quando a JFrame for redimencionada pelo usuário durante a exucução
        // da aplicação.
        // Chama Classe para redimencionamento da imagem de fundo da JFrame.
        this.imgJFrameLogin(false);
    }//GEN-LAST:event_formComponentResized

   
    
    // Método para inicializar a aplicação java.
    private void inicializeAplication(){
        // As linhas abaixo setam as dimensoes dos icones das JLabel's.
        telaConf.fullScree(JPanelLogin.this);
        telaConf.imageRend(this.lblIcon, img2, 100, 100);
        telaConf.imageLabelRend(this.pnlLogin, this.lblImagemPnl, img1);
        this.imgJFrameLogin(true);
    }
    
    // Variavel seta imagem na tela princiapal de acordo com a etapa de execução.
    // true Para inicialização no construtor da classe.
    // false Para redimensionamento e minimização de JFrame.
    private void imgJFrameLogin(boolean notIsInicial){
        if(notIsInicial){
            
            telaConf.imageLabelRend(this.lblImageFrame, img);
        }else{
            //telaConf.imageLabelRend(TelaLogin.this, this.lblImageFrame, img);
            telaConf.imageLabelRend(this, this.lblImageFrame, img);
        }
       
    }
    
    


}
