/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;


/**
 *
 * @author Willian
 */
public class JPanelPrincipal extends javax.swing.JFrame {

	TelConf telaConf = new TelConf();
	// Cor quando o mouse entrar no JButton
	int ec = 103, ec1 = 103, ec2 = 103;
	// Cor quando o mouse sair do JButton
	int sc = 51, sc1 = 51, sc2 = 51;
	// Número do JButton clicado
	private int num = 2;

	private final String img = "/com/images/images_1.png";

	// ####################################################################################################################
	//
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton JButtonAddUsuarios;
	private JButton JButtonVeiculos;
	private JButton JButtonClientes;
	private JButton JButtonConfiguracao;
	private JButton JButtonFaturamento;
	private JButton JButtonIniciar;
	private JButton btnMBar;
	private JButton JButtonOS;
	private JButton JButtonOrcamento;
	private JButton jButton10;
	private JButton jButton11;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel JButtonIconeUsuario;
	private javax.swing.JLabel JButtonNomeUsuario;
	private javax.swing.JPanel pnlCenter;
	private javax.swing.JPanel pnlFirst;
	private javax.swing.JPanel pnlIniciar;
	private javax.swing.JPanel JPanelWestMenuLateral;
	private javax.swing.JPanel JPanelJButtonConfiguracao;
	private javax.swing.JPanel JPanelButtons;
	private javax.swing.JPanel pnl_iniciar;
	private javax.swing.JPanel JPanelWest;
	private javax.swing.JScrollPane JScrollWest;

	// End of variables declaration//GEN-END:variables
	/**
	 * Creates new form TelaPrincipal
	 */
	public JPanelPrincipal() {
		initComponents(); // inicializa os componentes da JFrame.
		// Metodo para configurar preferencias de componentes de JFrame.
		this.inicializeAplication();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	/**
	 * 
	 */
	/**
	 * 
	 */
	private void initComponents() {
		
		this.getJButtonIniciar();
		this.getJButtonOS();
		this.getJButtonOrcamento();
		this.getJButtonVeiculos();
		

		

		pnlIniciar.setLayout(new java.awt.BorderLayout());

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));
		setFocusCycleRoot(false);
		setFocusable(false);
		setFocusableWindowState(false);
		setLocationByPlatform(true);
		// setPreferredSize(new Dimension(800,600));
		setSize(new Dimension(1225, 937));

		JPanelWestMenuLateral.setBackground(new java.awt.Color(51, 51, 51));
		JPanelWestMenuLateral.setToolTipText("");
		JPanelWestMenuLateral.setName(""); // NOI18N
		JPanelWestMenuLateral.setPreferredSize(new java.awt.Dimension(265, 800));

		JPanelWest.setBackground(new java.awt.Color(0, 51, 51));
		JPanelWest.setBorder(null);
		JPanelWest.setOpaque(false);
		JPanelWest.setPreferredSize(new java.awt.Dimension(265, 200));

		JButtonIconeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		JButtonIconeUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/user_100.png"))); // NOI18N

		JButtonNomeUsuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
		JButtonNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
		JButtonNomeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		JButtonNomeUsuario.setText("Usuário");
		JButtonNomeUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		javax.swing.GroupLayout gl_JPanelWest = new javax.swing.GroupLayout(JPanelWest);
		JPanelWest.setLayout(gl_JPanelWest);
		gl_JPanelWest.setHorizontalGroup(gl_JPanelWest.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(JButtonNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(gl_JPanelWest
						.createSequentialGroup().addContainerGap(82, Short.MAX_VALUE).addComponent(JButtonIconeUsuario,
								javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(83, Short.MAX_VALUE)));
		gl_JPanelWest.setVerticalGroup(gl_JPanelWest.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_JPanelWest.createSequentialGroup().addContainerGap(31, Short.MAX_VALUE)
						.addComponent(JButtonIconeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 96,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(5, 5, 5)
						.addComponent(JButtonNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
						.addGap(12, 12, 12)));

		JScrollWest.setBackground(new java.awt.Color(51, 51, 51));
		JScrollWest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		JScrollWest.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		JScrollWest.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		JScrollWest.setViewportBorder(null);
		JScrollWest.setAutoscrolls(true);
		JScrollWest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		JScrollWest.setFocusCycleRoot(true);
		JScrollWest.setOpaque(true);
		JScrollWest.setPreferredSize(new java.awt.Dimension(265, 1100));

		JPanelButtons.setBackground(new java.awt.Color(51, 51, 51));
		JPanelButtons.setBorder(null);
		JPanelButtons.setPreferredSize(new java.awt.Dimension(265, 825));

		
		

		JPanelJButtonConfiguracao.setBackground(new Color(0, 0, 0));
		JPanelJButtonConfiguracao.setRequestFocusEnabled(false);
		JPanelJButtonConfiguracao.setVisible(false);
		javax.swing.GroupLayout gl_JPanelJButtonConfiguracao = new javax.swing.GroupLayout(JPanelJButtonConfiguracao);
		JPanelJButtonConfiguracao.setLayout(gl_JPanelJButtonConfiguracao);
		gl_JPanelJButtonConfiguracao.setHorizontalGroup(
				gl_JPanelJButtonConfiguracao.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(gl_JPanelJButtonConfiguracao.createSequentialGroup().addGap(1, 1, 1)
								.addGroup(gl_JPanelJButtonConfiguracao
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 219,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 219,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(1, 1, 1)));
		
		
		gl_JPanelJButtonConfiguracao.setVerticalGroup(
				gl_JPanelJButtonConfiguracao.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(gl_JPanelJButtonConfiguracao.createSequentialGroup().addGap(1, 1, 1)
								.addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(1, 1, 1).addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(1, 1, 1)));
		

		javax.swing.GroupLayout gl_JPanelButtons = new javax.swing.GroupLayout(JPanelButtons);
		gl_JPanelButtons.setHorizontalGroup(gl_JPanelButtons.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_JPanelButtons.createSequentialGroup().addContainerGap()
						.addGroup(gl_JPanelButtons.createParallelGroup(Alignment.LEADING)
								.addGroup(gl_JPanelButtons.createParallelGroup(Alignment.TRAILING)
										.addComponent(JButtonOS, GroupLayout.PREFERRED_SIZE, 219,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(JButtonIniciar, GroupLayout.PREFERRED_SIZE, 219,
												GroupLayout.PREFERRED_SIZE))
								.addComponent(JButtonFaturamento, GroupLayout.PREFERRED_SIZE, 219,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(JButtonOrcamento, GroupLayout.PREFERRED_SIZE, 219,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(JButtonVeiculos, GroupLayout.PREFERRED_SIZE, 219,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(JButtonClientes, GroupLayout.PREFERRED_SIZE, 219,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(JButtonAddUsuarios, GroupLayout.PREFERRED_SIZE, 219,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(JButtonConfiguracao, GroupLayout.PREFERRED_SIZE, 219,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(JPanelJButtonConfiguracao, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addContainerGap(32, Short.MAX_VALUE)));
		gl_JPanelButtons.setVerticalGroup(gl_JPanelButtons.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_JPanelButtons.createSequentialGroup().addGap(6)
						.addComponent(JButtonIniciar, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(JButtonOS, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(JButtonOrcamento, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(JButtonVeiculos, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(JButtonClientes, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
						.addGap(7)
						.addComponent(JButtonAddUsuarios, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
						.addGap(13)
						.addComponent(JButtonFaturamento, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(JButtonConfiguracao, GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE).addGap(168)
						.addComponent(JPanelJButtonConfiguracao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		JPanelButtons.setLayout(gl_JPanelButtons);

		JScrollWest.setViewportView(JPanelButtons);

		javax.swing.GroupLayout gl_JPanelWestMenuLateral = new javax.swing.GroupLayout(JPanelWestMenuLateral);
		JPanelWestMenuLateral.setLayout(gl_JPanelWestMenuLateral);
		gl_JPanelWestMenuLateral.setHorizontalGroup(
				gl_JPanelWestMenuLateral.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(JPanelWest, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(JScrollWest, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
		gl_JPanelWestMenuLateral.setVerticalGroup(
				gl_JPanelWestMenuLateral.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(gl_JPanelWestMenuLateral.createSequentialGroup()
								.addComponent(JPanelWest, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(JScrollWest, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)));

		getContentPane().add(JPanelWestMenuLateral, java.awt.BorderLayout.WEST);

		pnlFirst.setBackground(new java.awt.Color(219, 131, 0));
		pnlFirst.setPreferredSize(new java.awt.Dimension(1027, 60));

		

		javax.swing.GroupLayout pnlFirstLayout = new javax.swing.GroupLayout(pnlFirst);
		pnlFirst.setLayout(pnlFirstLayout);
		pnlFirstLayout
				.setHorizontalGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlFirstLayout.createSequentialGroup()
								.addComponent(btnMBar, javax.swing.GroupLayout.PREFERRED_SIZE, 65,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(1142, Short.MAX_VALUE)));
		pnlFirstLayout.setVerticalGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlFirstLayout.createSequentialGroup().addComponent(btnMBar,
						javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		getContentPane().add(pnlFirst, java.awt.BorderLayout.PAGE_START);

		pnlCenter.setBackground(new java.awt.Color(255, 255, 255));
		pnlCenter.setLayout(new javax.swing.OverlayLayout(pnlCenter));

		pnl_iniciar.setLayout(new java.awt.BorderLayout());

		jLabel4.setBackground(new java.awt.Color(255, 255, 255));
		jLabel4.setForeground(new java.awt.Color(102, 102, 102));
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/images_1.png"))); // NOI18N
		jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jLabel4.setOpaque(true);
		pnl_iniciar.add(jLabel4, java.awt.BorderLayout.CENTER);

		pnlCenter.add(pnl_iniciar);

		getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

		setBounds(0, 0, 1225, 869);
	}// </editor-fold>//GEN-END:initComponents
		//
		// #########################################################################################################################################

	

	private void inicializeAplication() {
		telaConf.fullScree(this);
	}

	private void open(JPanel panel, int wdt_close, int wdt_open, int hgt) {
		panel.setSize(wdt_close, hgt);
		Thread thread;
		thread = new Thread() {

			@Override
			public void run() {
				try {
					for (int i = wdt_close; i <= wdt_open; i++) {
						Thread.sleep(1);
						panel.setSize(i, hgt);
					}
				} catch (Exception e) {
					JOptionPane.showMessageDialog(null, e);
				}
			}
		};
		thread.start();
	}

	private void close(JPanel panel, int wdt_close, int wdt_open, int hgt) {
		panel.setSize(wdt_open, hgt);
		Thread thread;
		thread = new Thread() {

			@Override
			public void run() {
				try {
					for (int i = wdt_open; i >= wdt_close; i--) {
						Thread.sleep(1);
						panel.setSize(i, hgt);
					}
				} catch (Exception e) {
					JOptionPane.showMessageDialog(null, e);
				}
			}
		};
		thread.start();

	}


	private void btnClick(int num) {
		this.num = num;
		if (num != 1)
			this.setColor(51, 51, 51);
		int c = 103;
		int c1 = 103;
		int c2 = 103;
		switch (num) {
		case 1:
			this.btnMBar.setBackground(new Color(109, 65, 0));
			break;
		case 2:
			this.JButtonIniciar.setBackground(new Color(c, c1, c2));
			break;
		case 3:
			this.JButtonOS.setBackground(new Color(c, c1, c2));
			break;
		case 4:
			this.JButtonOrcamento.setBackground(new Color(c, c1, c2));
			break;
		case 5:
			this.JButtonVeiculos.setBackground(new Color(c, c1, c2));
			break;
		case 6:
			this.JButtonClientes.setBackground(new Color(c, c1, c2));
			break;
		case 7:
			this.JButtonAddUsuarios.setBackground(new Color(c, c1, c2));
			break;
		case 8:
			this.JButtonFaturamento.setBackground(new Color(c, c1, c2));
			break;

		case 9:
			this.JButtonConfiguracao.setBackground(new Color(c, c1, c2));
			break;
		}
	}

	private void setColor(int c, int c1, int c2) {
		this.JButtonIniciar.setBackground(new Color(c, c1, c2));
		this.JButtonOS.setBackground(new Color(c, c1, c2));
		this.JButtonOrcamento.setBackground(new Color(c, c1, c2));
		this.JButtonVeiculos.setBackground(new Color(c, c1, c2));
		this.JButtonClientes.setBackground(new Color(c, c1, c2));
		this.JButtonAddUsuarios.setBackground(new Color(c, c1, c2));
		this.JButtonFaturamento.setBackground(new Color(c, c1, c2));
		this.JButtonConfiguracao.setBackground(new Color(c, c1, c2));
	}

	private void mouseExited(JButton btn, int numEx) {
		System.out.format("mouseExited: num = %s, numEx = %s", (int) num, (int) numEx);
		if (num != numEx) {
			btn.setBackground(new Color(sc, sc1, sc2));
		}
	}
	

	public JButton getBtnMBar() {
		if (btnMBar == null) {
			btnMBar = new JButton();
			btnMBar.setBackground(new java.awt.Color(219, 131, 0));
			btnMBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/menu_64.png"))); // NOI18N
			btnMBar.setBorder(null);
			btnMBar.setBorderPainted(false);
			btnMBar.setContentAreaFilled(false);
			btnMBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			btnMBar.setDisabledIcon(null);
			btnMBar.setDisabledSelectedIcon(null);
			btnMBar.setOpaque(true);
			
		}
		return btnMBar;
	}

	
	public JButton getJButtonIniciar() {
		if (JButtonIniciar == null) {
			JButtonIniciar = new JButton();
			JButtonIniciar.setBackground(new java.awt.Color(103, 103, 103));
			JButtonIniciar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			JButtonIniciar.setForeground(new java.awt.Color(204, 204, 204));
			JButtonIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/home_48.png"))); // NOI18N
			JButtonIniciar.setText(" Iniciar");
			JButtonIniciar.setBorder(null);
			JButtonIniciar.setBorderPainted(false);
			JButtonIniciar.setContentAreaFilled(false);
			JButtonIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonIniciar.setHideActionText(true);
			JButtonIniciar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			JButtonIniciar.setOpaque(true);
		}
		return JButtonIniciar;
	}
	
	
	public JButton getJButtonOS() {
		if (JButtonOS == null) {
			JButtonOS = new JButton();
			JButtonOS.setBackground(new java.awt.Color(51, 51, 51));
			JButtonOS.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			JButtonOS.setForeground(new java.awt.Color(204, 204, 204));
			JButtonOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/OS_48.png"))); // NOI18N
			JButtonOS.setText(" O.S");
			JButtonOS.setBorder(null);
			JButtonOS.setBorderPainted(false);
			JButtonOS.setContentAreaFilled(false);
			JButtonOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonOS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			JButtonOS.setOpaque(true);
		}
		return JButtonOS;
	}
	
	public JButton getJButtonOrcamento() {
		if (JButtonOrcamento == null) {
			JButtonOrcamento = new JButton();
			JButtonOrcamento.setBackground(new java.awt.Color(51, 51, 51));
			JButtonOrcamento.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			JButtonOrcamento.setForeground(new java.awt.Color(204, 204, 204));
			JButtonOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/orca_car_48.png"))); // NOI18N
			JButtonOrcamento.setText(" Orçamento");
			JButtonOrcamento.setBorder(null);
			JButtonOrcamento.setBorderPainted(false);
			JButtonOrcamento.setContentAreaFilled(false);
			JButtonOrcamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonOrcamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			JButtonOrcamento.setOpaque(true);
		}
		return JButtonOrcamento;
	}
	public JButton getJButtonVeiculos() {
		if (JButtonVeiculos == null) {
			JButtonVeiculos = new JButton();
			JButtonVeiculos.setBackground(new java.awt.Color(51, 51, 51));
			JButtonVeiculos.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			JButtonVeiculos.setForeground(new java.awt.Color(204, 204, 204));
			JButtonVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/car_48_1.png"))); // NOI18N
			JButtonVeiculos.setText(" Ve\u00EDculos");
			JButtonVeiculos.setBorder(null);
			JButtonVeiculos.setBorderPainted(false);
			JButtonVeiculos.setContentAreaFilled(false);
			JButtonVeiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonVeiculos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		}
		return JButtonVeiculos;
	}
	

	public JButton getJButtonClientes() {
		if (JButtonClientes == null) {
			JButtonClientes = new JButton();
			JButtonClientes.setBackground(new java.awt.Color(51, 51, 51));
			JButtonClientes.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			JButtonClientes.setForeground(new java.awt.Color(204, 204, 204));
			JButtonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/users_48.png"))); // NOI18N
			JButtonClientes.setText(" Clientes");
			JButtonClientes.setBorder(null);
			JButtonClientes.setBorderPainted(false);
			JButtonClientes.setContentAreaFilled(false);
			JButtonClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			JButtonClientes.setOpaque(true);
		}
		return JButtonClientes;
	}

	
	public JButton getJButtonFaturamento() {
		if (JButtonFaturamento == null) {
			JButtonFaturamento = new JButton();
			JButtonFaturamento.setBackground(new Color(51, 51, 51));
			JButtonFaturamento.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); 
			JButtonFaturamento.setForeground(new Color(204, 204, 204));
			JButtonFaturamento.setIcon(new ImageIcon(getClass().getResource("/com/icons/estimate-48.png"))); 
			JButtonFaturamento.setText(" Faturamento");
			JButtonFaturamento.setBorder(null);
			JButtonFaturamento.setBorderPainted(false);
			JButtonFaturamento.setContentAreaFilled(false);
			JButtonFaturamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonFaturamento.setHorizontalAlignment(SwingConstants.LEFT);
			JButtonFaturamento.setOpaque(true);
			
		}
		return JButtonFaturamento;
	}

	
	public JButton getJButtonAddUsuarios() {
		if (JButtonAddUsuarios == null) {
			JButtonAddUsuarios = new JButton();
			JButtonAddUsuarios.setBackground(new java.awt.Color(51, 51, 51));
			JButtonAddUsuarios.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			JButtonAddUsuarios.setForeground(new java.awt.Color(204, 204, 204));
			JButtonAddUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/use_conf_48.png"))); // NOI18N
			JButtonAddUsuarios.setText(" Usuário");
			JButtonAddUsuarios.setBorder(null);
			JButtonAddUsuarios.setBorderPainted(false);
			JButtonAddUsuarios.setContentAreaFilled(false);
			JButtonAddUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			JButtonAddUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			JButtonAddUsuarios.setOpaque(true);
			
		}
		return JButtonAddUsuarios;
	}
	
	
		
	public JButton getJButtonConfiguracao() {
		if (JButtonConfiguracao == null) {
			JButtonConfiguracao = new JButton();
			JButtonConfiguracao.setBackground(new Color(51, 51, 51));
			JButtonConfiguracao.setFont(new Font("Trebuchet MS", 1, 18));
			JButtonConfiguracao.setForeground(new Color(204, 204, 204));
			JButtonConfiguracao.setIcon(new ImageIcon(getClass().getResource("/com/icons/conf_48.png")));
			JButtonConfiguracao.setText(" Configura��es");
			JButtonConfiguracao.setBorder(null);
			JButtonConfiguracao.setBorderPainted(false);
			JButtonConfiguracao.setContentAreaFilled(false);
			JButtonConfiguracao.setCursor(new Cursor(Cursor.HAND_CURSOR));
			JButtonConfiguracao.setHorizontalAlignment(SwingConstants.LEFT);
			JButtonConfiguracao.setOpaque(true);
			
		}
		return JButtonConfiguracao;
	}

	public JButton getjButton10() {
		if (jButton10 == null) {
			jButton10 = new JButton();
			jButton10.setBackground(new java.awt.Color(204, 204, 204));
			jButton10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			jButton10.setText(" Cliente");
			jButton10.setBorder(null);
			jButton10.setBorderPainted(false);
			jButton10.setContentAreaFilled(false);
			jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			jButton10.setOpaque(true);
		}
		return jButton10;
	}



	public JButton getjButton11() {
		if (jButton11 == null) {
			jButton11 = new JButton();
			jButton11.setBackground(new java.awt.Color(204, 204, 204));
			jButton11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
			jButton11.setText(" Cliente");
			jButton11.setBorder(null);
			jButton11.setBorderPainted(false);
			jButton11.setContentAreaFilled(false);
			jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
			jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			jButton11.setOpaque(true);
		}
		return jButton11;
	}

	
	
	
}


